In [2]:
print("haioooooo")

haioooooo


In [3]:
pip install numpy

     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ------ --------------------------------- 10.2/61.0 kB ? eta -:--:--
     ------------------- ------------------ 30.7/61.0 kB 325.1 kB/s eta 0:00:01
     ------------------------------- ------ 51.2/61.0 kB 372.4 kB/s eta 0:00:01
     -------------------------------------- 61.0/61.0 kB 360.3 kB/s eta 0:00:00
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB

In [5]:
import numpy

In [77]:
#to get odd numbers
list1=numpy.array([1,2,3,4,5,6,7])
print(list1[::2])

[1 3 5 7]


In [8]:
list2=numpy.array(["pen","pencil","book"])

In [9]:
print(list2)

['pen' 'pencil' 'book']


In [10]:
type(list1)

numpy.ndarray

In [11]:
tuple1=numpy.array((1,2,3,4))

In [12]:
print(tuple1)

[1 2 3 4]


In [13]:
type(tuple1)

numpy.ndarray

In [16]:
b=numpy.array(4)
print(a)

4


In [21]:
#2d array
a=numpy.array([[1,2,3],[4,5,6]])

print(a)

[[1 2 3]
 [4 5 6]]


In [22]:
#3D array
c=numpy.array([[[1,2,3],[4,5,6]],[[1,3,4],[1,5,7]]])
print(c)

[[[1 2 3]
  [4 5 6]]

 [[1 3 4]
  [1 5 7]]]


In [24]:
d=numpy.array([[[9,8,7],[0,6,5]],[[4,5,6],[6,7,8]]])
print(d)

[[[9 8 7]
  [0 6 5]]

 [[4 5 6]
  [6 7 8]]]


In [27]:
import numpy as np

In [95]:
#find dimension
p=np.array([1,2,3,4])
print(p.ndim)

1


In [32]:
#create wanted no.of dimensions
p=np.array([1,2,3,4],ndmin=25)
print(p)


[[[[[[[[[[[[[[[[[[[[[[[[[1 2 3 4]]]]]]]]]]]]]]]]]]]]]]]]]


In [35]:
g=np.array([2,3,4,7,8])
print(g[1]+g[3])

10


In [94]:
#0:2 is list number and 1:4 is elements to be taken
#e.shape used to determine no.of rows and coolumn
e=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(e[0:2,1:4])
print(e.shape)
print(e)

[[2 3 4]
 [7 8 9]]
(2, 5)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [50]:
y=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12,]]])
print(y[1,1,1])

11


In [106]:
#convert data type
#here int convrt to str
import numpy as np
arr=np.array([1,2,3,4,5],dtype='S')
print(arr)


[b'1' b'2' b'3' b'4' b'5']


In [107]:

#to convert float to int
s=np.array([1.2,3.4,5.6])
v=s.astype("i")
print(v)

[1 3 5]


In [112]:
l=np.array([1,2,3,5,0])
x=l.astype("bool")
print(x)

[ True  True  True  True False]


In [122]:
#change shape of matrix
n=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
m=n.reshape(6,2)
print(m)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [96]:
#no.of elements
#in 2D no.f rows and columns
#in 3D no.f list row and column
n=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(n.shape)

(12,)


In [123]:
n=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
m=n.reshape(2,3,2)
print(m)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [128]:
hh=np.array([2,3,4,5,6])
uu=np.array([7,8,9,0,2])
kk=np.concatenate((hh,uu))
print(kk)


[2 3 4 5 6 7 8 9 0 2]


In [135]:
#to change row and column
ww=np.array([[2,3,4,6,2],[5,6,7,7,8]])
dd=np.array([[9,3,2,6,2],[8,6,4,7,8]])
mm=np.stack((ww,dd),axis=1)
print(mm)

[[[2 3 4 6 2]
  [5 6 7 7 8]]

 [[9 3 2 6 2]
  [8 6 4 7 8]]]


In [133]:
#combine two array
ww=np.array([[2,3,4,6,2],[5,6,7,7,8]])
dd=np.array([[9,3,2,6,2],[8,6,4,7,8]])
mm=np.stack((ww,dd))
print(mm)

[[[2 3 4 6 2]
  [5 6 7 7 8]]

 [[9 3 2 6 2]
  [8 6 4 7 8]]]


In [136]:
ww=np.array([[2,3,4,6,2],[5,6,7,7,8]])
dd=np.array([[9,3,2,6,2],[8,6,4,7,8]])
mm=np.concatenate((ww,dd),axis=1)
print(mm)

[[2 3 4 6 2 9 3 2 6 2]
 [5 6 7 7 8 8 6 4 7 8]]


In [138]:
#row combined comes first
ww=np.array([[2,3,4,6,2],[5,6,7,7,8]])
dd=np.array([[9,3,2,6,2],[8,6,4,7,8]])
mm=np.hstack((ww,dd))
print(mm)

[[2 3 4 6 2 9 3 2 6 2]
 [5 6 7 7 8 8 6 4 7 8]]


In [139]:
#column combined comes first
ww=np.array([[2,3,4,6,2],[5,6,7,7,8]])
dd=np.array([[9,3,2,6,2],[8,6,4,7,8]])
mm=np.vstack((ww,dd))
print(mm)

[[2 3 4 6 2]
 [5 6 7 7 8]
 [9 3 2 6 2]
 [8 6 4 7 8]]


In [ ]:
d=numpy.array([[[9,8,7],[0,6,5]],[[4,5,6],[6,7,8]]])
print(d)

[[[9 8 7]
  [0 6 5]]

 [[4 5 6]
  [6 7 8]]]


In [140]:

#hieghtwise combinun
ww=np.array([[2,3,4,6,2],[5,6,7,7,8]])
dd=np.array([[9,3,2,6,2],[8,6,4,7,8]])
mm=np.dstack((ww,dd))
print(mm)

[[[2 9]
  [3 3]
  [4 2]
  [6 6]
  [2 2]]

 [[5 8]
  [6 6]
  [7 4]
  [7 7]
  [8 8]]]


In [142]:
woww= np.array([2,3,4,5,6,7,3,9,5,6,8,2,0])
qq=np.array_split(woww,3)
print(qq)

[array([2, 3, 4, 5, 6]), array([7, 3, 9, 5]), array([6, 8, 2, 0])]


In [148]:
rar=np.zeros((2,3,2))
print(rar)

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [149]:
lo=np.ones((2,3,2))
print(lo)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [152]:
tt=np.ones((3,2))
print(tt)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [97]:
#can use flting num also
import numpy as np
oi=np.arange(10,20,2)
print(oi)

[10 12 14 16 18]


In [16]:
#equally divides the number
sa=np.linspace(1,76,4)
print(sa)

[ 1. 26. 51. 76.]


In [25]:
#matrix using same element
daa=np.full((3,3),12)
print(daa)

[[12 12 12]
 [12 12 12]
 [12 12 12]]


In [56]:
#2 by 2 matrix containing random element btw 20 and 50
vi=np.random.randint(20,50,(2,2))
print(vi)

[[31 27]
 [23 45]]


In [57]:
fien=np.random.randint(10,30,(7,7))
print(fien)

[[12 14 13 26 12 10 29]
 [26 11 17 14 29 10 25]
 [19 28 11 18 10 18 27]
 [10 19 25 23 23 29 26]
 [26 20 13 13 26 12 24]
 [13 20 25 14 18 24 23]
 [11 17 25 16 22 18 13]]


In [93]:
#matrix using random numbers btw 0 and 1
wwe=np.random.random((4,6))
print(wwe)

[[0.97124085 0.46504653 0.24719703 0.87195587 0.27925961 0.48345978]
 [0.79115768 0.56159704 0.24724512 0.1014816  0.07386345 0.9491528 ]
 [0.76241253 0.71046321 0.9166219  0.72838614 0.16845411 0.90643617]
 [0.53878621 0.47729502 0.23312791 0.20759551 0.71045598 0.60772712]]
